### PR TITLE
fix: deactivate item when is not open

### PR DESCRIPTION
**Pull request by YurandCL**
#### What problem is this solving?

When we have a item hovered (active) and move the mouse to another element very fast, sometimes the `isActive` state does not change to false, because in evaluation `onMountBehaviorFlag==="close"` `onMountBehaviorFlag` sometimes comes to undefined

#### How to test it?

[Workspace](https://ycl--poccarrefourarg.myvtex.com/

#### Screenshots or example usage:
before:

https://user-images.githubusercontent.com/40153830/226982476-ef39c350-918c-49e5-b204-a7e3ccb902d1.mp4

---
after:

https://user-images.githubusercontent.com/40153830/226982492-577a66b1-d4c8-4458-a88a-1e1beae6e135.mp4

### CODE REVIEW

**Comment by filipewl** [comment]
Hey @YurandCL, thank you for the contribution!

Could you please update the `CHANGELOG.md` file with a description of your changes? [Here's an example](https://github.com/vtex-apps/menu/pull/178#issuecomment-1487086706).

**Review by filipewl — COMMENTED** [review]
Looking good! You just need to update the `CHANGELOG.md` file.

**Comment by YurandCL** [comment]
Hey @filipewl.
I updated the `CHANGELOG.md` file, sorry I forgot to do it before. 😅

**Review by filipewl — APPROVED** [review]

**Comment by filipewl** [comment]
Replaced by #179.

**Pull request closed without merging**
